

export const products: ProductType[] = [
  {
    id: 1,
    category: "electronics",
    name: "Wireless Earbuds",
    description: "High-quality wireless earbuds with noise cancellation.",
    price: 59.99,
    image: [
      {
        id: 1,
        name: "Earbuds Image",
        description: "Earbuds",
        src: "earbuds.jpg",
      },
    ],
    inventory: 50,
    rating: 4.5,
    review: [{ id: 1, rating: 5, comment: "Great sound quality!" }],
    quantity: 0,
    colors: ["black", "white"],
  },
  {
    id: 2,
    category: "clothing",
    name: "Men's T-Shirt",
    description: "Soft cotton t-shirt available in multiple colors.",
    price: 19.99,
    image: [
      {
        id: 2,
        name: "T-Shirt Image",
        description: "T-Shirt",
        src: "tshirt.jpg",
      },
    ],
    inventory: 200,
    rating: 4.2,
    review: [{ id: 2, rating: 4, comment: "Comfortable and affordable." }],
    quantity: 0,
    sizes: ["S", "M", "L", "XL"],
    colors: ["blue", "red", "green"],
  },
  {
    id: 3,
    category: "groceies",
    name: "Organic Honey",
    description: "Pure organic honey sourced from natural farms.",
    price: 14.99,
    image: [
      {
        id: 3,
        name: "Honey Image",
        description: "Organic Honey",
        src: "honey.jpg",
      },
    ],
    inventory: 100,
    rating: 4.8,
    review: [{ id: 3, rating: 5, comment: "Delicious and healthy!" }],
    quantity: 0,
    colors: [],
  },
  {
    id: 4,
    category: "accessories",
    name: "Leather Wallet",
    description: "Premium leather wallet with multiple card slots.",
    price: 34.99,
    image: [
      {
        id: 4,
        name: "Wallet Image",
        description: "Leather Wallet",
        src: "wallet.jpg",
      },
    ],
    inventory: 150,
    rating: 4.6,
    review: [{ id: 4, rating: 5, comment: "Great quality leather!" }],
    quantity: 0,
    colors: ["brown", "black"],
  },
  {
    id: 5,
    category: "jewelry",
    name: "Silver Necklace",
    description: "Elegant silver necklace with a minimalist design.",
    price: 79.99,
    image: [
      {
        id: 5,
        name: "Necklace Image",
        description: "Silver Necklace",
        src: "necklace.jpg",
      },
    ],
    inventory: 80,
    rating: 4.7,
    review: [{ id: 5, rating: 4, comment: "Looks beautiful." }],
    quantity: 0,
    colors: ["silver"],
  },
  {
    id: 6,
    category: "office supplies",
    name: "Ergonomic Chair",
    description: "Adjustable ergonomic chair for office use.",
    price: 129.99,
    image: [
      {
        id: 6,
        name: "Chair Image",
        description: "Ergonomic Chair",
        src: "chair.jpg",
      },
    ],
    inventory: 20,
    rating: 4.4,
    review: [{ id: 6, rating: 5, comment: "Perfect for long work hours." }],
    quantity: 0,
    colors: ["black", "gray"],
  },
  {
    id: 7,
    category: "shoes",
    name: "Running Shoes",
    description: "Lightweight running shoes with excellent grip.",
    price: 69.99,
    image: [
      {
        id: 7,
        name: "Running Shoes Image",
        description: "Running Shoes",
        src: "runningshoes.jpg",
      },
    ],
    inventory: 120,
    rating: 4.3,
    review: [{ id: 7, rating: 4, comment: "Good for jogging and daily use." }],
    quantity: 0,
    sizes: ["8", "9", "10", "11"],
    colors: ["blue", "black"],
  },
  {
    id: 8,
    category: "books",
    name: "Mystery Novel",
    description: "A gripping mystery novel by a best-selling author.",
    price: 12.99,
    image: [
      {
        id: 8,
        name: "Book Image",
        description: "Mystery Novel",
        src: "mysterynovel.jpg",
      },
    ],
    inventory: 300,
    rating: 4.5,
    review: [{ id: 8, rating: 5, comment: "Couldn't put it down!" }],
    quantity: 0,
    colors: [],
  },
  {
    id: 9,
    category: "home & kitchen",
    name: "Air Fryer",
    description: "Compact air fryer with multiple cooking modes.",
    price: 99.99,
    image: [
      {
        id: 9,
        name: "Air Fryer Image",
        description: "Air Fryer",
        src: "airfryer.jpg",
      },
    ],
    inventory: 60,
    rating: 4.6,
    review: [{ id: 9, rating: 5, comment: "Makes healthy cooking easy!" }],
    quantity: 0,
    colors: ["black", "white"],
  },
  {
    id: 10,
    category: "beauty",
    name: "Face Serum",
    description: "Hydrating face serum for glowing skin.",
    price: 24.99,
    image: [
      {
        id: 10,
        name: "Serum Image",
        description: "Face Serum",
        src: "serum.jpg",
      },
    ],
    inventory: 90,
    rating: 4.7,
    review: [{ id: 10, rating: 5, comment: "My skin feels amazing!" }],
    quantity: 0,
    colors: [],
  },
  {
    id: 11,
    category: "stationery",
    name: "Gel Pens Set",
    description: "Set of 12 smooth gel pens for writing and drawing.",
    price: 7.99,
    image: [
      {
        id: 11,
        name: "Gel Pens Image",
        description: "Gel Pens Set",
        src: "gelpens.jpg",
      },
    ],
    inventory: 250,
    rating: 4.5,
    review: [{ id: 11, rating: 4, comment: "Writes smoothly." }],
    quantity: 0,
    colors: ["multicolor"],
  },
  {
    id: 12,
    category: "beverages",
    name: "Herbal Tea",
    description: "Relaxing herbal tea with natural ingredients.",
    price: 9.99,
    image: [
      { id: 12, name: "Tea Image", description: "Herbal Tea", src: "tea.jpg" },
    ],
    inventory: 150,
    rating: 4.6,
    review: [{ id: 12, rating: 5, comment: "Very soothing!" }],
    quantity: 0,
    colors: [],
  },
  {
    id: 13,
    category: "health & beauty",
    name: "Moisturizing Lotion",
    description: "All-day moisturizing lotion for soft skin.",
    price: 15.99,
    image: [
      {
        id: 13,
        name: "Lotion Image",
        description: "Moisturizing Lotion",
        src: "lotion.jpg",
      },
    ],
    inventory: 110,
    rating: 4.8,
    review: [{ id: 13, rating: 5, comment: "Keeps my skin hydrated all day." }],
    quantity: 0,
    colors: [],
  },
  {
    id: 14,
    category: "food & drink",
    name: "Gourmet Chocolate",
    description: "Luxury dark chocolate with a rich flavor.",
    price: 5.49,
    image: [
      {
        id: 14,
        name: "Chocolate Image",
        description: "Gourmet Chocolate",
        src: "chocolate.jpg",
      },
    ],
    inventory: 300,
    rating: 4.9,
    review: [{ id: 14, rating: 5, comment: "Best chocolate ever!" }],
    quantity: 0,
    colors: [],
  },
  {
    id: 15,
    category: "fashion",
    name: "Sunglasses",
    description: "Stylish sunglasses with UV protection.",
    price: 25.99,
    image: [
      {
        id: 15,
        name: "Sunglasses Image",
        description: "Sunglasses",
        src: "sunglasses.jpg",
      },
    ],
    inventory: 75,
    rating: 4.4,
    review: [{ id: 15, rating: 4, comment: "Very fashionable." }],
    quantity: 0,
    colors: ["black", "brown"],
  },
  {
    id: 16,
    category: "toys",
    name: "Building Blocks Set",
    description: "Colorful building blocks for creative play.",
    price: 29.99,
    image: [
      {
        id: 16,
        name: "Blocks Image",
        description: "Building Blocks Set",
        src: "blocks.jpg",
      },
    ],
    inventory: 150,
    rating: 4.8,
    review: [{ id: 16, rating: 5, comment: "Great for kids!" }],
    quantity: 0,
    colors: ["multicolor"],
  },
  {
    id: 17,
    category: "sports",
    name: "Yoga Mat",
    description: "Non-slip yoga mat with cushioning for comfort.",
    price: 20.99,
    image: [
      {
        id: 17,
        name: "Yoga Mat Image",
        description: "Yoga Mat",
        src: "yogamat.jpg",
      },
    ],
    inventory: 80,
    rating: 4.7,
    review: [{ id: 17, rating: 5, comment: "Perfect for my workouts." }],
    quantity: 0,
    colors: ["purple", "blue", "green"],
  },
  {
    id: 18,
    category: "pets",
    name: "Dog Chew Toy",
    description: "Durable chew toy for dogs of all sizes.",
    price: 12.49,
    image: [
      {
        id: 18,
        name: "Dog Toy Image",
        description: "Dog Chew Toy",
        src: "dogtoy.jpg",
      },
    ],
    inventory: 60,
    rating: 4.5,
    review: [{ id: 18, rating: 4, comment: "My dog loves it!" }],
    quantity: 0,
    colors: ["orange", "green"],
  },
  {
    id: 19,
    category: "music",
    name: "Acoustic Guitar",
    description: "Beginner-friendly acoustic guitar with a rich sound.",
    price: 199.99,
    image: [
      {
        id: 19,
        name: "Guitar Image",
        description: "Acoustic Guitar",
        src: "guitar.jpg",
      },
    ],
    inventory: 20,
    rating: 4.4,
    review: [{ id: 19, rating: 5, comment: "Great value for beginners." }],
    quantity: 0,
    colors: ["natural wood", "black"],
  },
  {
    id: 20,
    category: "other",
    name: "Digital Alarm Clock",
    description: "Multi-functional digital alarm clock with LED display.",
    price: 14.99,
    image: [
      {
        id: 20,
        name: "Clock Image",
        description: "Digital Alarm Clock",
        src: "clock.jpg",
      },
    ],
    inventory: 100,
    rating: 4.3,
    review: [{ id: 20, rating: 4, comment: "Works well and looks nice." }],
    quantity: 0,
    colors: ["white", "black"],
  },
  {
    id: 21,
    category: "electronics",
    name: "Smartwatch",
    description: "Feature-rich smartwatch with fitness tracking.",
    price: 89.99,
    image: [
      {
        id: 21,
        name: "Smartwatch Image",
        description: "Smartwatch",
        src: "smartwatch.jpg",
      },
    ],
    inventory: 45,
    rating: 4.5,
    review: [
      { id: 21, rating: 5, comment: "Great for keeping track of activities." },
    ],
    quantity: 0,
    colors: ["black", "silver"],
  },
  {
    id: 22,
    category: "clothing",
    name: "Summer Dress",
    description: "Lightweight summer dress with floral prints.",
    price: 34.99,
    image: [
      {
        id: 22,
        name: "Dress Image",
        description: "Summer Dress",
        src: "dress.jpg",
      },
    ],
    inventory: 90,
    rating: 4.6,
    review: [{ id: 22, rating: 5, comment: "Perfect for sunny days." }],
    quantity: 0,
    sizes: ["S", "M", "L"],
    colors: ["yellow", "blue"],
  },
  {
    id: 23,
    category: "groceies",
    name: "Organic Olive Oil",
    description: "Cold-pressed organic extra virgin olive oil.",
    price: 10.99,
    image: [
      {
        id: 23,
        name: "Olive Oil Image",
        description: "Organic Olive Oil",
        src: "oliveoil.jpg",
      },
    ],
    inventory: 130,
    rating: 4.8,
    review: [{ id: 23, rating: 5, comment: "High quality and great taste!" }],
    quantity: 0,
    colors: [],
  },
  {
    id: 24,
    category: "accessories",
    name: "Wristwatch",
    description: "Stylish wristwatch with a leather band.",
    price: 45.99,
    image: [
      {
        id: 24,
        name: "Wristwatch Image",
        description: "Wristwatch",
        src: "wristwatch.jpg",
      },
    ],
    inventory: 50,
    rating: 4.4,
    review: [{ id: 24, rating: 4, comment: "Looks elegant." }],
    quantity: 0,
    colors: ["black", "brown"],
  },
  {
    id: 25,
    category: "jewelry",
    name: "Gold Bracelet",
    description: "18k gold bracelet with a sleek design.",
    price: 149.99,
    image: [
      {
        id: 25,
        name: "Bracelet Image",
        description: "Gold Bracelet",
        src: "bracelet.jpg",
      },
    ],
    inventory: 30,
    rating: 4.8,
    review: [{ id: 25, rating: 5, comment: "Beautiful piece of jewelry!" }],
    quantity: 0,
    colors: ["gold"],
  },
  {
    id: 26,
    category: "office supplies",
    name: "Desk Organizer",
    description: "Multi-compartment desk organizer for stationery.",
    price: 15.49,
    image: [
      {
        id: 26,
        name: "Organizer Image",
        description: "Desk Organizer",
        src: "organizer.jpg",
      },
    ],
    inventory: 100,
    rating: 4.5,
    review: [{ id: 26, rating: 4, comment: "Keeps my desk tidy." }],
    quantity: 0,
    colors: ["black", "white"],
  },
  {
    id: 27,
    category: "shoes",
    name: "Casual Sneakers",
    description: "Comfortable sneakers for daily wear.",
    price: 54.99,
    image: [
      {
        id: 27,
        name: "Sneakers Image",
        description: "Casual Sneakers",
        src: "sneakers.jpg",
      },
    ],
    inventory: 120,
    rating: 4.5,
    review: [{ id: 27, rating: 5, comment: "Very comfortable and stylish." }],
    quantity: 0,
    sizes: ["7", "8", "9", "10"],
    colors: ["white", "navy"],
  },
  {
    id: 28,
    category: "books",
    name: "Cookbook",
    description: "A collection of healthy and delicious recipes.",
    price: 18.99,
    image: [
      {
        id: 28,
        name: "Cookbook Image",
        description: "Cookbook",
        src: "cookbook.jpg",
      },
    ],
    inventory: 220,
    rating: 4.7,
    review: [
      { id: 28, rating: 5, comment: "Great recipes for all occasions." },
    ],
    quantity: 0,
    colors: [],
  },
  {
    id: 29,
    category: "home & kitchen",
    name: "Blender",
    description: "High-speed blender for smoothies and more.",
    price: 49.99,
    image: [
      {
        id: 29,
        name: "Blender Image",
        description: "Blender",
        src: "blender.jpg",
      },
    ],
    inventory: 60,
    rating: 4.6,
    review: [{ id: 29, rating: 5, comment: "Works like a charm!" }],
    quantity: 0,
    colors: ["silver", "black"],
  },
  {
    id: 30,
    category: "beauty",
    name: "Lip Balm",
    description: "Moisturizing lip balm with natural ingredients.",
    price: 3.99,
    image: [
      {
        id: 30,
        name: "Lip Balm Image",
        description: "Lip Balm",
        src: "lipbalm.jpg",
      },
    ],
    inventory: 200,
    rating: 4.9,
    review: [{ id: 30, rating: 5, comment: "Keeps my lips soft all day." }],
    quantity: 0,
    colors: ["pink", "clear"],
  },
  {
    id: 31,
    category: "stationery",
    name: "Notebook",
    description: "Hardcover notebook with lined pages.",
    price: 6.99,
    image: [
      {
        id: 31,
        name: "Notebook Image",
        description: "Notebook",
        src: "notebook.jpg",
      },
    ],
    inventory: 300,
    rating: 4.6,
    review: [{ id: 31, rating: 5, comment: "Ideal for journaling." }],
    quantity: 0,
    colors: ["blue", "red", "black"],
  },
  {
    id: 36,
    category: "beverages",
    name: "Organic Green Tea",
    description: "Refreshing organic green tea with antioxidants.",
    price: 8.99,
    image: [
      {
        id: 36,
        name: "Green Tea Image",
        description: "Organic Green Tea",
        src: "greentea.jpg",
      },
    ],
    inventory: 150,
    rating: 4.7,
    review: [{ id: 36, rating: 5, comment: "Tastes great and feels healthy!" }],
    quantity: 0,
    colors: [],
  },
  {
    id: 37,
    category: "health & beauty",
    name: "Vitamin C Serum",
    description: "Brightening serum for glowing skin.",
    price: 22.99,
    image: [
      {
        id: 37,
        name: "Serum Image",
        description: "Vitamin C Serum",
        src: "serum.jpg",
      },
    ],
    inventory: 95,
    rating: 4.9,
    review: [
      { id: 37, rating: 5, comment: "My skin has never looked better!" },
    ],
    quantity: 0,
    colors: ["orange"],
  },
  {
    id: 38,
    category: "food & drink",
    name: "Gourmet Chocolate Box",
    description: "Assorted premium chocolates for all tastes.",
    price: 14.99,
    image: [
      {
        id: 38,
        name: "Chocolate Box Image",
        description: "Gourmet Chocolate Box",
        src: "chocolates.jpg",
      },
    ],
    inventory: 130,
    rating: 4.8,
    review: [
      { id: 38, rating: 5, comment: "Delicious and perfect for gifts." },
    ],
    quantity: 0,
    colors: [],
  },
  {
    id: 39,
    category: "fashion",
    name: "Leather Wallet",
    description: "Classic leather wallet with multiple compartments.",
    price: 29.99,
    image: [
      {
        id: 39,
        name: "Wallet Image",
        description: "Leather Wallet",
        src: "wallet.jpg",
      },
    ],
    inventory: 75,
    rating: 4.5,
    review: [{ id: 39, rating: 4, comment: "Great quality leather." }],
    quantity: 0,
    colors: ["brown", "black"],
  },
  {
    id: 40,
    category: "home & kitchen",
    name: "Electric Kettle",
    description: "Fast-boil electric kettle with automatic shut-off.",
    price: 34.99,
    image: [
      {
        id: 40,
        name: "Kettle Image",
        description: "Electric Kettle",
        src: "kettle.jpg",
      },
    ],
    inventory: 60,
    rating: 4.6,
    review: [{ id: 40, rating: 5, comment: "Heats water quickly and safely." }],
    quantity: 0,
    colors: ["white", "stainless steel"],
  },
  {
    id: 41,
    category: "stationery",
    name: "Gel Pens Set",
    description: "Pack of 12 colorful gel pens for smooth writing.",
    price: 7.99,
    image: [
      {
        id: 41,
        name: "Gel Pens Image",
        description: "Gel Pens Set",
        src: "gelpens.jpg",
      },
    ],
    inventory: 140,
    rating: 4.7,
    review: [{ id: 41, rating: 5, comment: "Love the vibrant colors!" }],
    quantity: 0,
    colors: ["multicolor"],
  },
  {
    id: 42,
    category: "toys",
    name: "Remote-Controlled Car",
    description: "High-speed RC car with rechargeable battery.",
    price: 49.99,
    image: [
      {
        id: 42,
        name: "RC Car Image",
        description: "Remote-Controlled Car",
        src: "rccar.jpg",
      },
    ],
    inventory: 45,
    rating: 4.5,
    review: [{ id: 42, rating: 4, comment: "My son loves it!" }],
    quantity: 0,
    colors: ["red", "blue"],
  },
  {
    id: 43,
    category: "sports",
    name: "Basketball",
    description: "Official size and weight basketball for all courts.",
    price: 24.99,
    image: [
      {
        id: 43,
        name: "Basketball Image",
        description: "Basketball",
        src: "basketball.jpg",
      },
    ],
    inventory: 90,
    rating: 4.6,
    review: [{ id: 43, rating: 5, comment: "Good grip and bounce." }],
    quantity: 0,
    colors: ["orange"],
  },
  {
    id: 44,
    category: "pets",
    name: "Cat Scratching Post",
    description: "Durable scratching post to keep cats entertained.",
    price: 25.49,
    image: [
      {
        id: 44,
        name: "Scratching Post Image",
        description: "Cat Scratching Post",
        src: "catpost.jpg",
      },
    ],
    inventory: 55,
    rating: 4.7,
    review: [{ id: 44, rating: 5, comment: "My cat loves it!" }],
    quantity: 0,
    colors: ["beige", "gray"],
  },
  {
    id: 45,
    category: "music",
    name: "Headphones",
    description: "Noise-cancelling over-ear headphones for immersive sound.",
    price: 79.99,
    image: [
      {
        id: 45,
        name: "Headphones Image",
        description: "Headphones",
        src: "headphones.jpg",
      },
    ],
    inventory: 30,
    rating: 4.5,
    review: [{ id: 45, rating: 4, comment: "Great sound quality." }],
    quantity: 0,
    colors: ["black", "white"],
  },
  {
    id: 46,
    category: "electronics",
    name: "Portable Speaker",
    description: "Bluetooth speaker with excellent sound quality.",
    price: 59.99,
    image: [
      {
        id: 46,
        name: "Speaker Image",
        description: "Portable Speaker",
        src: "speaker.jpg",
      },
    ],
    inventory: 40,
    rating: 4.6,
    review: [{ id: 46, rating: 5, comment: "Perfect for parties." }],
    quantity: 0,
    colors: ["black", "red", "blue"],
  },
  {
    id: 47,
    category: "beauty",
    name: "Makeup Brush Set",
    description: "10-piece professional makeup brush set.",
    price: 16.99,
    image: [
      {
        id: 47,
        name: "Brush Set Image",
        description: "Makeup Brush Set",
        src: "makeupbrush.jpg",
      },
    ],
    inventory: 85,
    rating: 4.8,
    review: [{ id: 47, rating: 5, comment: "Soft and perfect for blending." }],
    quantity: 0,
    colors: ["black", "rose gold"],
  },
  {
    id: 48,
    category: "clothing",
    name: "Winter Jacket",
    description: "Warm and cozy winter jacket with a hood.",
    price: 69.99,
    image: [
      {
        id: 48,
        name: "Jacket Image",
        description: "Winter Jacket",
        src: "jacket.jpg",
      },
    ],
    inventory: 60,
    rating: 4.7,
    review: [
      { id: 48, rating: 5, comment: "Keeps me warm in freezing temperatures." },
    ],
    quantity: 0,
    sizes: ["M", "L", "XL"],
    colors: ["black", "navy", "gray"],
  },
  {
    id: 49,
    category: "food & drink",
    name: "Gourmet Coffee Beans",
    description: "Premium roasted coffee beans for a rich flavor.",
    price: 15.99,
    image: [
      {
        id: 49,
        name: "Coffee Beans Image",
        description: "Gourmet Coffee Beans",
        src: "coffeebeans.jpg",
      },
    ],
    inventory: 70,
    rating: 4.9,
    review: [{ id: 49, rating: 5, comment: "Best coffee I've ever had!" }],
    quantity: 0,
    colors: [],
  },
  {
    id: 50,
    category: "fashion",
    name: "Silk Scarf",
    description: "Elegant silk scarf with floral patterns.",
    price: 24.99,
    image: [
      {
        id: 50,
        name: "Scarf Image",
        description: "Silk Scarf",
        src: "scarf.jpg",
      },
    ],
    inventory: 110,
    rating: 4.8,
    review: [{ id: 50, rating: 5, comment: "Beautiful and lightweight." }],
    quantity: 0,
    colors: ["red", "blue", "green"],
  },
];
